stages:
  - build
  - test

image: docker:latest
services:
  - docker:dind


backend_build:
  stage: build
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker pull aquiles23/backend_image
  script: 
    - docker build --cache-from aquiles23/backend_image ./backend/
    - docker push aquiles23/backend_image

frontend_build:
  stage: build
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS  
    - docker pull aquiles23/frontend_image
  script: 
    - docker build --cache-from aquiles23/frontend_image ./frontend/
    - docker push aquiles23/frontend_image

backend_test:
  stage: test
  image: node:lts
  before_script:
    - cd backend
    - npm install
  script: npm run unittest

frontend_test:
  stage: test
  image: node:14
  before_script:
    - cd frontend
    - yarn
  script: yarn test