stages:
  - build
  - test


backend_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script: docker build ./backend/

frontend_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script: docker build ./frontend/

backend_test:
  stage: test
  script: echo "example"
