
services:
  - docker:dind

stages:
  - build
  - test
  - pushImage
  
backend_build:
  stage: build
  # image: postgres
  script: docker build ./backend/

frontend_build:
  stage: build
  script: docker build ./frontend/