stages:
  - build
  - test

image: docker:latest
services:
  - docker:dind

before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

backend_build:
  stage: build
  script: 
    - docker build ./backend/
    - docker push backend_image:latest

frontend_build:
  stage: build
  script: 
    - docker build ./frontend/
    - docker push frontend_image:latest

backend_test:
  stage: test
  image: node:lts
  before_script:
    - cd backend
    - npm install
  script: npm run unittest

frontend_test:
  stage: test
  image: node:14
  before_script:
    - cd frontend
    - yarn
  script: yarn test