stages:
  - build
  - test
image: docker:latest
services:
  - docker:dind


backend_build:
  stage: build
  script: docker build ./backend/

frontend_build:
  stage: build
  script: docker build ./frontend/

backend_test:
  stage: test
  image: node:lts
  before_script:
    - cd backend
    - npm install
  script: npm run unittest
