stages:
  - build
  - test
  - pushImage
  
backend_build:
  image: docker:dind
  stage: build
  # image: postgres
  script: docker build ./backend/

frontend_build:
  image: docker:dind
  stage: build
  script: docker build ./frontend/

backend_test:
  stage: test
  script: echo "example"

backend_pushImage:
  stage: pushImage
  script: echo "example 2"