version: '3'

services:
  database:
    image: postgres
    ports:
      - '8000:5432'
    env_file: .env
    networks: 
      - network_app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - database
    networks:
      - network_app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - '3030:3000'
    networks:
      - network_app

networks:
  network_app:
